export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CATEGORY_SELECTED = 'CATEGORY_SELECTED';
export const PAGE_SELECTED = 'PAGE_SELECTED';
export const SHOW_CART = 'SHOW_CART';
